### ISSUE TITLE
[Question] Custom fonts?

### ISSUE THREAD

**Issue by haunt98** [catppuccin/github#48]
How can I custom interface font (different than Inter) and monospace font?

**Comment by rubyowo** [comment]
```css
	body,.markdown-body {
    	font-family: <font>, sans-serif;
	}
```
